const curYr = new Date().getFullYear();

export const roadmapKeywords = [
  `Full Stack Roadmap ${curYr}`,
  "Student Developer Roadmap",
  `Developer Career Guide ${curYr}`,
  "How to Get Hired as a Developer",
  "College to Software Developer",
  "Build Developer Portfolio",
  `Junior Developer Skills ${curYr}`,
  "Modern Developer Skills",
  "Open Source for Beginners",
  "First GitHub Contribution",
  "GitHub vs GPA",
  "Student Career in Tech",
];

export const reactNextKeywords = [
  "Next.js Beginner Tutorials",
  "Next.js App Router Guide",
  "Learn Next.js for Students",
  "React for Beginners",
  "React Hooks Explained",
  "useState Tutorial",
  "useEffect Tutorial",
  `React Hooks ${curYr}`,
  "Server Components vs Client Components",
  "Next.js Server Components",
  "Deploy Next.js App",
  "Vercel Deployment Guide",
  "Free Hosting for Next.js",
];

export const troubleshootingKeywords = [
  "TypeScript Basics",
  "Learn TypeScript for Students",
  "Type Safety in React",
  "Common React Bugs",
  "Fix React Errors",
  "React Debugging Guide",
  "Tailwind CSS Best Practices",
  "Tailwind CSS Tips",
  "Clean UI with Tailwind",
  "API Fundamentals",
  "Fetch API in React",
  "Display API Data in React",
];

export const projectKeywords = [
  "Coding Projects for Beginners",
  "Next.js Portfolio Projects",
  "Real Time Chat App",
  "WebSockets with Next.js",
  "SaaS Dashboard Project",
  "Impress Recruiters with Projects",
  "Expense Tracker React",
  "Full Stack Project for Students",
  "React Node.js Project",
  "AI Powered Portfolio",
  "Next.js AI Integration",
  "Gemini API Next.js",
  "Student Portfolio Projects",
];

export const blogsKeywords = [
  "Step-by-Step Web Development Tutorials",
  "JavaScript Fundamentals for Students",
  "Building your first Next.js App",
  "Understanding React Server Components simply",
  "TypeScript for Beginners Tutorial",
  "Explain Like I'm Five (ELI5) Coding Concepts",
  "How to contribute to GitHub for beginners",
  "Common Interview Questions for Frontend Developers",
  `Best free resources to learn Web Dev  ${curYr}`,
  "Coding Best Practices for Students",
  "CSS Grid and Flexbox Explained",
  "Data Structures in JavaScript Guide",
  `Web Development Trends ${curYr}`,
  "Full Stack Development Roadmap",
  "Next.js App Router Tutorials",
  "Advanced React Patterns and Best Practices",
  "Mastering TypeScript Generics",
  "How to use React Server Components", // Educational Intent (Long-tail)
  "Building AI Chatbots with Node.js",
  "Optimizing Core Web Vitals for Next.js",
  "Clean Code Architecture in JavaScript",
  "Secure Authentication in React Apps",
  "Generative UI with Vercel v0",
  "Edge Runtime vs Serverless Functions",
  "Vibe Coding and AI-Native Engineering",
  "Agentic UI Design Patterns",
  `Zero-Runtime CSS in ${curYr}`,
  "Step-by-Step Web Development Tutorials",
  "JavaScript Fundamentals for Students",
  "Building your first Next.js App",
  "Understanding React Server Components simply",
  "TypeScript for Beginners Tutorial",
  "Explain Like I'm Five (ELI5) Coding Concepts",
  "How to contribute to GitHub for beginners",
  "Common Interview Questions for Frontend Developers",
  `Best free resources to learn Web Dev ${curYr}`,
  "Coding Best Practices for Students",
  "CSS Grid and Flexbox Explained",
  "Data Structures in JavaScript Guide",
  `Web Development for Beginners ${curYr}`,
  "Learn Full Stack Development Step-by-Step",
  "Coding Roadmap for College Students",
  "Best Projects for Developer Portfolios",
  "Free Web Development Resources for Students",
  "How to Learn React and Next.js Fast",
  "Junior Developer Interview Preparation",
  "Understanding Web Development Fundamentals",
  "Programming Career Guide for Students",
  "TypeScript for Absolute Beginners",
  "React Server Components Explained Simply",
  "Tailwind CSS Tutorial for New Developers",
  "JavaScript ES6 Features You Must Know",
  "Next.js App Router Guide for Beginners",
  "How to Connect Frontend to Backend",
  "GitHub Basics for Student Developers",
  "Database Basics for Web Applications",
  "Job-Winning Portfolio Projects",
  "How to Get Your First Developer Internship",
  "Coding Best Practices for Junior Developers",
  "Writing Clean Code in Your First Project",
  "How to Contribute to Open Source as a Student",
  "Building a Personal Brand as a Developer",
  "Resume Tips for Software Engineering Students",
  `What is the best tech stack to learn in  ${curYr}`,
  "How to build a web application from scratch",
  "Why is TypeScript better than JavaScript for beginners?",
  `The easiest way to learn Next.js in ${curYr}`,
  "How much coding should I know to get a job?",
  "Learn Web Development",
  `Student Developer Roadmap ${curYr}`,
  "Next.js Beginner Tutorials",
  "React for Students",
  "How to Build a Portfolio",
  "Junior Developer Career Guide",
  "Coding Projects for Beginners",
  "TypeScript Basics",
  "Open Source for Students",
];

export const allBlogKeywords = [
  ...blogsKeywords,
  ...roadmapKeywords,
  ...reactNextKeywords,
  ...troubleshootingKeywords,
  ...projectKeywords,
];
